
Development:
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate
  SBD_RESULTS_PATH: "/data/share/maxrecall_vhh_mmsi/videos/results/sbd/final_results/final_shots_video-counter-24fps.csv"
  SAVE_DEBUG_PKG: 0

PreProcessing:
  RESIZE_DIM: 128, 128      # resize dimension -> height, width
  MEAN_VAL: [94.05657, 94.05657, 94.05657]  # mean values per color channel
  STD_DEV: [57.99793, 57.99793, 57.99793]   # standard deviation per color channel

StcCore:
  CLASS_NAMES: ["ELS","LS","MS","CU"]
  BATCH_SIZE: 64
  SAVE_RAW_RESULTS: 1       # 1 ... yes 0 ... no
  PATH_RAW_RESULTS: "/data/share/maxrecall_vhh_mmsi/videos/results/stc/raw_results/"
  NUMBER_OF_FRAMES_PER_SHOT: 5  # save x frames per shot
  PREFIX_RAW_RESULTS: "results_raw_"
  POSTFIX_RAW_RESULTS: "csv"

  SAVE_FINAL_RESULTS: 1     # 1 ... yes 0 ... no
  PATH_FINAL_RESULTS: "/data/share/maxrecall_vhh_mmsi/videos/results/stc/final_results/"
  PREFIX_FINAL_RESULTS: "results_"
  POSTFIX_FINAL_RESULTS: "csv"

  PATH_VIDEOS: "/data/share/maxrecall_vhh_mmsi/videos/downloaded/"
  THRESHOLD: 0.8                 # value [0-1]

  PATH_PRETRAINED_MODEL: "/data/share/maxrecall_vhh_mmsi/videos/pre_trained_models/stc/20200207_BasicCNN_db_v8_Vgg_ExpNum_001/"
  #PATH_PRETRAINED_MODEL: "/home/dhelm/VHH_Develop/installed_pkg/stc/pre_trained_models/20191223_BasicCNN_Vgg_Imagenet_ExpNum_2/"

Evaluation:
  SAVE_EVAL_RESULTS: 1
  PATH_RAW_RESULTS: "/data/share/maxrecall_vhh_mmsi/videos/results/sbd/raw_results/"
  PATH_EVAL_RESULTS: "/data/share/maxrecall_vhh_mmsi/videos/results/sbd/develop/"
  PATH_GT_ANNOTATIONS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/annotations/ShotBoundaryDetection/imediacities/sbd_imc_annotations_20191231.csv"
